

### Term and condition API 
POST http://localhost:5000/api/v1/register HTTP/1.1
Content-type: application/json

{
    "name": "javed",
    "about": "jhgdfh",
    "role": "user" ,
    "password" : "javed@123",
    "phone": "1111112111",
    "email" : "javedk3han199331440@gmail.com"
}



### Term and condition API 
POST http://localhost:5000/api/v1/login HTTP/1.1
Content-type: application/json

{
    "email":"javedk3han199331440@gmail.com",
    "password":"javed@123"
}


### Term and condition API 
POST http://162.215.253.215:8000/api/signin  HTTP/1.1
Content-type: application/json

{
    "email":"javedk3han199331440@gmail.com",
    "password":"javed@123"
}

